name: pocketbase_drift
description: A powerful, offline-first PocketBase client backed by a drift database.
version: 0.3.11
repository: https://github.com/DrDejaVuNG/pocketbase_drift
issue_tracker: https://github.com/DrDejaVuNG/pocketbase_drift/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  logging: ^1.3.0
  connectivity_plus: ^7.0.0
  pocketbase: ^0.23.1
  drift: ^2.30.0
  sqlite3_flutter_libs: ^0.5.41
  path_provider: ^2.1.5
  path: ^1.9.1
  sqlite3: ^2.9.4
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.7.2
  drift_dev: ^2.30.0

flutter:

flutter_scripts:
  schema: flutter pub run drift_dev schema dump lib/src/database/database.dart drift_schemas/

topics:
  - pocketbase
  - offline
  - cache
  - drift